name = "mylive-sync"
main = "src/index.js"
compatibility_date = "2025-01-01"
routes = [{ pattern = "mylive.conef.hidns.co/*", zone_name = "conef.hidns.co" }]

[[durable_objects.bindings]]
name = "SYNC_ROOM"
class_name = "SyncRoom"

[[migrations]]
tag = "v1"
new_classes = ["SyncRoom"]
